### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [keandreheard/prj-rev-bwfs-dasmoto#6]
https://github.com/keandreheard/prj-rev-bwfs-dasmoto/blob/master/DevProject/style.css#L1-L17

Nice job using more general selectors like `html` and `h2` so that you can consolidate shared styles in one location and keep your CSS tidy and maintainable. 👍 

If you'd used `div` tags with the same class, you could write the following selector which is a little more specific than `h2` in case you later introduce `h2` tags that should be styled differently from the ones in the product sections.

```css
.product h2 {
  font-size: 32px;
  font-weight: bold;
  color: white;
}
```
